services:
  backend:
    build: ./Backend
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=postgres://postgres:pass@db:5432/flight_booking
    depends_on:
      - db

  frontend:
    build: ./Frontend
    ports:
      - '5173:5173'
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: flight_booking
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
