name: CI - Backend

on:
  push:
    branches: ['production']
    paths:
      - '**/*'
  pull_request:
    branches: ['production']
    paths:
      - '**/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Create .env file
        run: |
          cd Backend
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

      - name: Install dependencies
        run: |
          cd Backend
          npm install

      - name: Run Linter
        run: |
          cd Backend
          npm run lint

      - name: Run Tests
        run: |
          cd Backend
          npm test

  deploy-to-cloud-run:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: devops-workshop-462511

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Build and push Backend Docker image
        run: |
          docker build -t gcr.io/devops-workshop-462511/flights-backend Backend/
          docker push gcr.io/devops-workshop-462511/flights-backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flights-backend \
            --image gcr.io/devops-workshop-462511/flights-backend \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }}"
