name: CI - Backend

on:
  push:
    branches: ['main', 'development', 'production']
    paths:
      # Trigger workflow only when files in the Backend directory change
      - 'Backend/**'
  pull_request:
    branches: ['main', 'development', 'production']
    paths:
      # Trigger workflow only when files in the Backend directory change
      - 'Backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Create .env file for backend with database URL
      - name: Create .env file
        run: |
          cd Backend
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

      # Install backend dependencies
      - name: Install dependencies
        run: |
          cd Backend
          npm install

      # Run linter for code quality
      - name: Run Linter
        run: |
          cd Backend
          npm run lint

      # Run unit and integration tests
      - name: Run Unit and Integration Tests
        run: |
          cd Backend
          npm test

  deploy-to-cloud-run:
    needs: build-and-test
    runs-on: ubuntu-latest
    # Deploy only on main or production branches
    if: github.ref == 'refs/heads/production' || github.ref == 'refs/heads/main'
    steps:
      # Checkout the code again for deployment
      - name: Checkout code
        uses: actions/checkout@v4

      # Authenticate to Google Cloud using service account key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: devops-workshop-462511

      # Configure Docker to push to Google Container Registry
      - name: Configure Docker for GCR
        run: gcloud auth configure-docker gcr.io --quiet

      # Build and push the backend Docker image to GCR
      - name: Build and push Backend Docker image
        run: |
          docker build -t gcr.io/devops-workshop-462511/flights-backend Backend/
          docker push gcr.io/devops-workshop-462511/flights-backend

      # Deploy the backend image to Google Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flights-backend \
            --image gcr.io/devops-workshop-462511/flights-backend \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }}"
